import React, { useState, useCallback, useMemo } from 'react';
import {
  Brain,
  Sparkles,
  CheckCircle,
  Loader2,
  X,
} from 'lucide-react';
import { SAMPLE_RECOMMENDATIONS } from '../../data/dummyData';
import MedicationCard from './MedicationCard';
import AIChatPanel from './AIChatPanel';
import FormCard from '../ui/FormCard';
import Button from '../ui/Button';

/**
 * Recommendation List — displays AI-generated medication recommendations
 * alongside a collapsible AI chat panel for clinical decision support.
 */
export default function RecommendationList({ patientData }) {
  const [recommendations, setRecommendations] = useState(null);
  const [loading, setLoading] = useState(false);
  const [actionedMap, setActionedMap] = useState({});
  const [modifyModal, setModifyModal] = useState(null);
  const [modDose, setModDose] = useState('');
  const [chatOpen, setChatOpen] = useState(true);
  const [chatDrugContext, setChatDrugContext] = useState(null);

  const generateRecs = useCallback(() => {
    setLoading(true);
    setActionedMap({});
    // Simulate API call
    setTimeout(() => {
      setRecommendations(SAMPLE_RECOMMENDATIONS);
      setLoading(false);
    }, 1800);
  }, []);

  const handleAccept = useCallback(
    (id) => {
      setActionedMap((p) => ({ ...p, [id]: { action: 'accepted' } }));
    },
    []
  );

  const handleReject = useCallback(
    (id) => {
      setActionedMap((p) => ({ ...p, [id]: { action: 'rejected' } }));
    },
    []
  );

  const handleModifyOpen = useCallback(
    (id) => {
      const rec = recommendations?.find((r) => r.id === id);
      if (rec) {
        setModifyModal(rec);
        setModDose(rec.originalDosage || '');
      }
    },
    [recommendations]
  );

  const handleModifySubmit = useCallback(() => {
    if (modifyModal && modDose.trim()) {
      setActionedMap((p) => ({
        ...p,
        [modifyModal.id]: { action: 'modified', detail: modDose },
      }));
      setModifyModal(null);
    }
  }, [modifyModal, modDose]);

  // group by category
  const grouped = useMemo(() => {
    if (!recommendations) return {};
    return recommendations.reduce((acc, rec) => {
      (acc[rec.category] = acc[rec.category] || []).push(rec);
      return acc;
    }, {});
  }, [recommendations]);

  const handleAskAI = useCallback(
    (id) => {
      const rec = recommendations?.find((r) => r.id === id);
      if (rec) {
        setChatDrugContext(rec);
        if (!chatOpen) setChatOpen(true);
      }
    },
    [recommendations, chatOpen]
  );

  const totalActioned = Object.keys(actionedMap).length;
  const totalRecs = recommendations?.length || 0;

  return (
    <div className="flex gap-4 items-start">
      {/* Recommendations column */}
      <div className="flex-1 min-w-0">
      <FormCard
        title="AI Recommendations"
        subtitle="Evidence-based medication recommendations generated by GLYERAL."
        accentColor="accent"
        headerSlot={
          !recommendations ? (
            <Button
              type="button"
              onClick={generateRecs}
              loading={loading}
              icon={<Brain className="w-4 h-4" />}
            >
              Generate Recommendations
            </Button>
          ) : (
            <div className="flex items-center gap-3">
              <span className="text-xs text-slate-500 bg-slate-100 px-3 py-1 rounded-full font-semibold">
                {totalActioned}/{totalRecs} reviewed
              </span>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={generateRecs}
                loading={loading}
              >
                Regenerate
              </Button>
            </div>
          )
        }
      >
        {/* Loading state */}
        {loading && (
          <div className="flex flex-col items-center gap-4 py-16 text-center animate-fade-in">
            <div className="w-14 h-14 bg-primary-50 rounded-2xl flex items-center justify-center border border-primary-100">
              <Loader2 className="w-7 h-7 text-primary-600 animate-spin" />
            </div>
            <div>
              <p className="text-lg font-bold text-slate-900">
                Analyzing Patient Data...
              </p>
              <p className="text-sm text-slate-500 mt-1">
                Cross-referencing ADA/KDIGO/AHA guidelines
              </p>
            </div>
          </div>
        )}

        {/* Empty state */}
        {!loading && !recommendations && (
          <div className="flex flex-col items-center gap-4 py-16 text-center">
            <div className="w-16 h-16 bg-primary-50 rounded-2xl flex items-center justify-center border border-primary-100">
              <Sparkles className="w-8 h-8 text-primary-500" />
            </div>
            <div>
              <p className="text-lg font-bold text-slate-900">
                Ready to Generate
              </p>
              <p className="text-sm text-slate-500 mt-1 max-w-md">
                Click the button above to generate AI-powered medication
                recommendations based on the patient's data.
              </p>
            </div>
          </div>
        )}

        {/* Recommendations list */}
        {!loading && recommendations && (
          <div className="space-y-6 stagger-children">
            {Object.entries(grouped).map(([category, recs]) => (
              <div key={category}>
                <h3 className="text-sm font-bold text-slate-600 mb-3 flex items-center gap-2 uppercase tracking-wide">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary-400" />
                  {category} Medications
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {recs.map((rec) => (
                    <MedicationCard
                      key={rec.id}
                      rec={rec}
                      onAccept={handleAccept}
                      onModify={handleModifyOpen}
                      onReject={handleReject}
                      onAskAI={handleAskAI}
                      actionedMap={actionedMap}
                    />
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Modify Modal */}
        {modifyModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm animate-fade-in">
            <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6 relative animate-scale-in mx-4">
              {/* Purple accent */}
              <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-primary-500 to-accent-500 rounded-t-2xl" />

              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900">
                    Modify Dosage
                  </h3>
                  <p className="text-sm text-slate-500 mt-0.5">
                    {modifyModal.med}
                  </p>
                </div>
                <button
                  onClick={() => setModifyModal(null)}
                  className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-all"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="space-y-3">
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1.5">
                    Original Dosage
                  </label>
                  <div className="px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-sm text-slate-500">
                    {modifyModal.dose}
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1.5">
                    Modified Dosage
                  </label>
                  <input
                    type="text"
                    value={modDose}
                    onChange={(e) => setModDose(e.target.value)}
                    className="w-full px-3.5 py-2.5 border-2 border-slate-200 rounded-xl focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500/15 text-sm"
                    placeholder="Enter new dosage..."
                    autoFocus
                  />
                </div>
              </div>

              <div className="mt-5 flex justify-end gap-3">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setModifyModal(null)}
                >
                  Cancel
                </Button>
                <Button
                  size="sm"
                  onClick={handleModifySubmit}
                  icon={<CheckCircle className="w-4 h-4" />}
                >
                  Save
                </Button>
              </div>
            </div>
          </div>
        )}
      </FormCard>
      </div>

      {/* AI Chat Panel */}
      <div className="sticky top-4">
        <AIChatPanel
          open={chatOpen}
          onToggle={() => setChatOpen((prev) => !prev)}
          recommendations={recommendations}
          actionedMap={actionedMap}
          drugContext={chatDrugContext}
          onClearContext={() => setChatDrugContext(null)}
        />
      </div>
    </div>
  );
}
